Changed the SyncProducer to AsyncProducer also renamed collector.go to output.go
grafana/xk6-output-kafka pull request #10
Opened 2021-09-08 17:46 UTC by knmsk

Hi!

@victorlcm and i changed a few things in order to improve the performance on the producer, We opened a issue some days ago #9.
The change on `collector.go` to `output.go`  to match the same structure as the others output available on the k6 (json, influxdb, csv and etc...)  to simplify the maintenance of the `xk6-output-kafka`;
Also we changed the SyncProducer to the AsyncProducer. We executed the test using 2500 VUs to run in 1m30s with both  producers. The process which runned the SyncProducer waited at least 10 minutes after printing the summary of the run to end the OS process. The Async one was almost on the same instant after finishing the exhibition of same summary to end the OS process. Each one sent at least 500k messages to the topic.

2021-09-09 07:45 UTC, MStoykov reviewed
Apart from not logging errors and reverting to exporting a struct that doesn't need it, it seems LGTM :tada: Thanks for the contribution. 

I would still like to get the error logging working and maybe @mostafa can test it as I am not really a kafka user :sweat_smile: .

2021-09-09 07:45 UTC, MStoykov commented on pkg/kafka/scram_client.go
> +type XDGSCRAMClient struct {
I guess this was just done as you had an old copy, but we really don't need this to me exported, so I prefer if we don't ;)

2021-09-09 07:45 UTC, MStoykov commented on pkg/kafka/output.go
> +	saramaConfig.Producer.Return.Errors = false
I would prefer if this is actually being read from so users can diagnose when things don't work ;)

2021-09-09 12:34 UTC, mostafa commented
@knmsk @victorlcm Thanks for your contribution!

@MStoykov I'll test it and let you know of the results.

2021-09-09 13:33 UTC, mostafa commented on pkg/kafka/output.go
> +	return fmt.Sprintf("Kafka: Kafka Sync output on topic %v", o.Config.Topic.String)
I think you should change the message here.

2021-09-09 13:36 UTC, mostafa commented
@MStoykov I tested it against [fast-data-dev](https://github.com/lensesio/fast-data-dev) and it worked well for a 10m test and 200 VUs with this script:

```javascript
import http from 'k6/http';
import { sleep } from 'k6';

export default function () {
  http.get('https://test.k6.io');
  sleep(1);
}
```

The results:

```shell
$ ./k6 run --vus 200 --duration 10m -o xk6-kafka=brokers={localhost:9092},topic=k6,format=json script.js

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: script.js
     output: Kafka: Kafka Sync output on topic k6

  scenarios: (100.00%) 1 scenario, 200 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 200 looping VUs for 10m0s (gracefulStop: 30s)


running (10m01.1s), 000/200 VUs, 107738 complete and 0 interrupted iterations
default ✓ [======================================] 200 VUs  10m0s

     data_received..................: 1.2 GB 2.0 MB/s
     data_sent......................: 14 MB  24 kB/s
     http_req_blocked...............: avg=1.06ms   min=120ns   med=280ns   max=1.48s    p(90)=340ns    p(95)=390ns

     http_req_connecting............: avg=418.25µs min=0s      med=0s      max=1.2s     p(90)=0s       p(95)=0s

     http_req_duration..............: avg=113.03ms min=92.35ms med=94.41ms max=6.02s    p(90)=102.04ms p(95)=102.83ms
       { expected_response:true }...: avg=113.03ms min=92.35ms med=94.41ms max=6.02s    p(90)=102.04ms p(95)=102.83ms
     http_req_failed................: 0.00%  ✓ 0          ✗ 107738
     http_req_receiving.............: avg=398.14µs min=20.14µs med=74.19µs max=4.88s    p(90)=756.59µs p(95)=1.08ms

     http_req_sending...............: avg=29.25µs  min=8.82µs  med=24.64µs max=1.46ms   p(90)=44.52µs  p(95)=57.09µs
     http_req_tls_handshaking.......: avg=516.26µs min=0s      med=0s      max=410.13ms p(90)=0s       p(95)=0s

     http_req_waiting...............: avg=112.6ms  min=91.84ms med=94.13ms max=6.02s    p(90)=101.73ms p(95)=102.5ms
     http_reqs......................: 107738 179.236217/s
     iteration_duration.............: avg=1.11s    min=1.09s   med=1.09s   max=7.02s    p(90)=1.1s     p(95)=1.1s

     iterations.....................: 107738 179.236217/s
     vus............................: 27     min=27       max=200
     vus_max........................: 200    min=200      max=200
```

2021-09-09 20:26 UTC, knmsk commented on pkg/kafka/output.go
> +	return fmt.Sprintf("Kafka: Kafka Sync output on topic %v", o.Config.Topic.String)
I've changed  to `xk6-kafka`, or is it better to only correct the `Sync` to `Async` what do you guys think?

2021-09-09 20:27 UTC, knmsk commented on pkg/kafka/output.go
> +	saramaConfig.Producer.Return.Errors = false
done, i've added a env for that `K6_KAFKA_LOG_ERROR` or argument as `log_error`

2021-09-09 20:27 UTC, knmsk commented on pkg/kafka/scram_client.go
> +type XDGSCRAMClient struct {
reverted this change!

2021-09-13 07:39 UTC, MStoykov commented on pkg/kafka/output.go
> +	}
This should be in the `Start` so it can log the errors over time. Obviously, it will also need to be in a separate goroutine so you will likely need to move this waitgroup in the Output and again wait for it on Close.

2021-09-13 12:26 UTC, knmsk commented on pkg/kafka/output.go
> +	}
I've tried to do in the `Start` function but the Error channel keeps waiting so the k6 won't start, also... when i tested this out the error channel only was populated when the producer closes. Can you help with this?

2021-09-13 13:20 UTC, MStoykov commented on pkg/kafka/output.go
> +	}
I've made a [PR](https://github.com/knmsk/xk6-output-kafka/pull/1) to this PR with the proposed changes

2021-09-13 13:40 UTC, knmsk commented on pkg/kafka/output.go
> +	}
I've been trying to fix thix but it happened a memory access error when i changed into that thx!

2021-09-13 15:55 UTC, codebien requested changes
Hey @knmsk,
it looks good to me, thanks for the contribution :sunglasses: 

Just reporting some small things.

2021-09-13 15:55 UTC, codebien commented on pkg/kafka/output.go
> +			for err := range o.Producer.Errors() {
Maybe we should mention the fact that not reading from this channel could generate a deadlock.

>// Errors is the error output channel back to the user. You MUST read from this
  // channel or the Producer will deadlock when the channel is full.
  
https://pkg.go.dev/github.com/shopify/sarama#AsyncProducer

2021-09-13 15:55 UTC, codebien commented on pkg/kafka/output.go
> +	Params          output.Params
Is it required? It seems not used.

2021-09-13 16:24 UTC, mostafa commented on pkg/kafka/output.go
> +	return fmt.Sprintf("Kafka: Kafka Sync output on topic %v", o.Config.Topic.String)
`Async` is enough, unless @MStoykov has a different opinion.

2021-09-13 16:30 UTC, MStoykov commented on pkg/kafka/output.go
> +	return fmt.Sprintf("Kafka: Kafka Sync output on topic %v", o.Config.Topic.String)
Yeah maybe just changing to `Async` and still keeping the topic is better ... I don't really know if it's better to be `xk6-Kafka:` in front but we can change that later ;)

2021-09-13 18:06 UTC, knmsk commented on pkg/kafka/output.go
> +			for err := range o.Producer.Errors() {
I think we can mention this in case someone doesn't read from the sarama documentations, the `saramaConfig.Producer.Return.Error` will be disabled if the LogError config  is false, so it will not be a problem.

2021-09-14 08:21 UTC, codebien commented on pkg/kafka/output.go
> +			for err := range o.Producer.Errors() {
Yes, I think a comment with them should be easier for the next contributor to catch these details.

2021-09-14 12:14 UTC, codebien approved these changes
LGTM

2021-09-14 12:23 UTC, MStoykov approved these changes
Thanks a lot for the work! I will now merge this :) 

And will open a PR for https://github.com/grafana/xk6-output-kafka/issues/13 which I expect won't be a breaking change for anyone but if you use the json config please note it in the issue

2021-09-14 12:23 UTC, merged