Feat/expose real metric type
grafana/xk6-output-kafka pull request #25
Opened 2023-09-05 17:54 UTC by dmcardoso

I was comparing the output of this extension and statsd output and i descovered that the exported type of metrics with the `xk6-output-kafka` is not the real metric type. Does it makes sense?

2023-09-05 17:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/xk6-output-kafka?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/xk6-output-kafka?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/xk6-output-kafka?pullRequest=25) it.</sub>

2023-09-07 07:29 UTC, mstoykov commented
This code was ripped from k6 core a couple of years ago. And big part of that was that AFAIK we did not really work on this code since it was added and nobody on the team was familiar with how this was supposed to work. But it still required maintainance and was addign to the binary size.

Since then there have been practically zero developmnet - only updating k6 versions and updating code so it compiles. 

I am not even certain if somebody uses this at all and how.

The changes proposed here will change the format of what is send - given that I have no idea how it is used and the amount of years this has been this way, I am against us making this change in this repo. I am not saying the change doesn't make sense, just that it will be a breaking one on a codebase I (and AFAIK anybody who has to approve this) uses or have used. 

This still means you can fork it and develop it including whatever changes you want.

I have @grafana/k6-ecosystem as this likely falls under their responsibilities. A good idea might be to find a user of this repo to take over as it doesn't seem that we will be working on this output at all.

2023-09-07 07:42 UTC, szkiba commented
I do not recommend this modification.
Apparently, the author wanted to use the json output extension format, which is why "Point" is included in the "type" property.
The json output extension sends the metric metadata in a separate object, where the value of the "type" property is "Metric" and the "data" property contains the metric metadata.
A better solution seems to be to imitate the operation of the json output extension and introduce the "type"="Metric" JSON object.

2023-09-07 07:44 UTC, szkiba requested changes
A better solution seems to be to imitate the operation of the json output extension and introduce the "type"="Metric" JSON object

2023-09-07 07:44 UTC, szkiba commented on pkg/kafka/format_json.go
> +		Type:   sample.Metric.Type.String(),
I do not recommend this modification.
Apparently, the author wanted to use the json output extension format, which is why "Point" is included in the "type" property.
The json output extension sends the metric metadata in a separate object, where the value of the "type" property is "Metric" and the "data" property contains the metric metadata.
A better solution seems to be to imitate the operation of the json output extension and introduce the "type"="Metric" JSON object.

2023-09-07 08:47 UTC, mstoykov commented on pkg/kafka/format_json.go
> +		Type:   sample.Metric.Type.String(),
This sounds reasonable and the types for this are internal to k6 [here](https://github.com/grafana/k6/blob/master/output/json/wrapper.go) so we can copy it here I guess. 

Again I can't say what the original idea was and how used it is as this predates me as change - we just moved it out of k6 as it was not really maitained.

2023-09-07 14:27 UTC, javaducky requested changes
Not passing the linter.

2023-10-20 14:42 UTC, javaducky commented
Hi @dmcardoso, just wanted to follow up and see if you're open to creating an issue describing the problem a bit more.  We are concerned about this breaking compatibility, so we want to encourage discussion within the community.

Additionally, there are linting errors with the submitted code changes.

2023-11-01 14:30 UTC, closed without merging

2023-11-01 14:30 UTC, javaducky commented
Closing as this is breaking change and desire feedback from the community.